### ISSUE TITLE
Discussion: C++ and Rust comparing

### ISSUE THREAD

**Issue by Marcus-Rise** [Sixthworks/spankerfield#12]
Is C++ a better language in this case than Rust? I want to learn rust, it's often compared to C++, and I'm trying to understand variants of implementation of this language.

**Comment by womblee** [comment]
C++ is way simpler and I think you should figure it out first, there is a high chance that you will waste a lot of time to get good at Rust.

I like Rust, but it’s a weird choice for memory hacking in a C++ code base. And syntax is way worse...

It can be a nice ass language like this:
```rust
let chlclient = crate::utils::interfaces::GetInterface::<*const tf2::engine::CHLClient>("./tf/bin/client.so", "VClient0").expect("Failed to get CHLClient's interface");
```
And then it can also be:
```rust
 let clientmode = unsafe { **(((*((*(chlclient as *mut *mut usize)).offset(10))) + 1) as *mut *mut *mut usize) };
```

Just learn c++👍

**Comment by womblee** [comment]
But it can be nice because it's fun* (type fun* not found, did you mean *const fn?)
