### ISSUE TITLE
Spankerfield doesnt inject with Xenos and gives error code

### ISSUE THREAD

**Issue by RealDawTheD** [Sixthworks/spankerfield#13]
If I inject it normally, I get an error code 0xC000135, if I inject with manual map, the game crashes. I used Xenos64 and tried other reliable injectors and none seem to work.

**Comment by womblee** [comment]
You can fix this error code by enabling or installing .NET Framework 3.5 on your Windows 11

**Comment by RealDawTheD** [comment]
I cannot install .net 3.5 on my Windows 10 machine

**Comment by RealDawTheD** [comment]
Installed .net 3.5 but still gives the error code
