### ISSUE TITLE
Crashing/Aimbot issue

### ISSUE THREAD

**Issue by tchokodornozov** [Sixthworks/spankerfield#14]
I guess the author of this is not into making changes to this anymore, as it's open source and a little old, but here are some problems that I can't fix as I never studied coding. 

WARNING: I am stupid and know nothing about what I'm saying

I noticed the program crashing in two particular "situations":

 1. With aimbot on: crashes faster. I noticed that the crash is more likely with aimbot on, sometimes I barely use it and it crashes.
 2. Suddenly: after some time of gameplay, it just closes. But I noticed that it tends to happen more towards the first minutes of a match, and if you get to play like 60% of the match, it's less likely that it's going to crash before the end. But for the next match, the chances are again increased until mid-game. (These are just some observations regarding 'when' it happens)

The log files are attached, and as you'll notice, one of then contains no error message, but it is too the log file for a crashed session, this makes me think that there's an unknown error going on and the program is not prepared to call it.
![image](https://github.com/Sixthworks/spankerfield/assets/138971430/24aceb86-efc6-491b-9420-a2b5985baaaa)
![image](https://github.com/Sixthworks/spankerfield/assets/138971430/14e6e398-89f3-44b0-b10d-49f42a4c5898)

--- 
 I haven't used all features enough, as all that matters to me is the aimbot (to 'compensate' for the shitty hitreg with a better aim, which is dumb as this is an aimbot and not aim assist) and sometimes the esp to roadkill people around. So I will point some failures and things to add or improve (regarding the aimbot), for those who know programming and haven't played enough to notice these problems. 
 
  1. The correction based on the bullet drop is faulty, it points above the target in situations where it shouldn't. In practice, this could be corrected by selecting a bone that sits lower in the body, but then it doesn't work properly, as those bones are covered by obstacles more often. In conclusion -generated with 0 knowledge and just guessing, I think the problem is associated with the math/poly_solver/w2s files. I changed the resolution from 1440p to 1080p (i dont remember where it is anymore) in the source code, but didn't correct the problem, although, with the possibly of placebo effect, it seems more consistent. Maybe it's calculating the bullet speed wrong?! Idk
  2. I think the aimbot deals badly with obstacles in practice, small boxes and windows are the nightmare for the functionality.
edit: forgot to mention that the aimbot also don't work well if your altitude is too different from the enemy, so, high ground kills are rarely going to happen with the aimbot enabled

**Comment by womblee** [comment]
This cheat is intended for legit gameplay, the aimbot code is not mine. I've added it just so people stop asking for it.

Please look at other cheats with aimbot.

Also if you looked at default aimbot settings, it is configured to act like aim assist since most servers will get you banned for obvious aimbotting.
