### ISSUE TITLE
Hey Quick Question.

### ISSUE THREAD

**Issue by X0I0** [Sixthworks/spankerfield#3]
Edit: Fixed My Original Issues. Is there a way where you can add which key is used for the aimbot, like left click, right click, alt ect ect, And I have no idea if this is a thing in BF4 but is there a Screenshot cleaner in this for the AC?

Reguards.

**Comment by X0I0** [comment]
Hey, Another Question my dude, What's wrong with the Aimbot?, has that got something to do with the overhead control? it seem's to just hinder using the ab than helping, it's strange, it's like the shot's are missing.

**Comment by ToasterPool** [comment]
> 

The reason for this is because the aimbot uses a old source (https://github.com/stevemk14ebr/BF4-AtomBot) so it will not be perfect. Try setting the aim bone to something like the thorax or spine.

**Comment by X0I0** [comment]
okie dokie, Thanks for the reply, i'll be sure to test some things.

**Comment by womblee** [comment]
I will be sure to paste a newer one.

**Comment by womblee** [comment]
Key can be set in settings.h
